### PR TITLE
Fixes and some cleanup in the python tools

### PR DESCRIPTION
**Pull request by tim-ist**
Fixes several problems with the TinyOS Python tools.

* USB and socket disconnection is now detected.
* Busy waiting loops (draining laptop battery) are removed.
* Fixed an issue on MacOS X related to the case-insensitive file system.
* Removed (not needed) code preventing binding with PyQT4.
* Other small fixes.

The code has been tested under high load on MacOS X (Maverics) and Debian GNU/Linux 7.8 .

### CODE REVIEW

**Comment by tim-ist** [comment]
Might be related to https://github.com/tinyos/tinyos-main/pull/282 and https://github.com/tinyos/tinyos-main/pull/259 .

**Comment by andrasbiro** [comment]
This seems impressive, and it's great that you reviewed the usually neglected python sdk.
Is someone responsible for the python stuff? Doesn anyone actively work with it?
If not, we probably should merge this. Any thoughts?

(the issues you linked are not related, that's a completely different sdk see the discussion in #259 - I think the best would be to rewrite the deluge tools and just drop the tos.py)

**Comment by gnawali** [comment]
lets merge

**Comment by cire831** [comment]
merge

On Wed, Apr 1, 2015 at 9:52 AM, gnawali <notifications@github.com> wrote:

> lets merge
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tinyos/tinyos-main/pull/335#issuecomment-88530732>.
>



-- 
Eric B. Decker
Senior (over 50 :-) Researcher

**Pull request merged**
