### PR TITLE
Fix sim.extra regex to match Python 2.7.x where x is two digits

### PR DESCRIPTION
**Pull request by MBradbury**
Fix sim.extra regex to match Python 2.7.x versions where x is two digits. Also support Python 3 and development versions of Python.

I posted this fix to the tinyos.users mailing list, but the post hasn't been approved yet. See the thread at: https://www.millennium.berkeley.edu/pipermail/tinyos-help/2017-January/059055.html

### CODE REVIEW

**Comment by MBradbury** [comment]
Actually it was intended. On my fork I added support for Python 3 and thought it would be easier to catch any digit, rather than just 2 or 3.

**Comment by cire831** [comment]
does it break anything?

**Comment by MBradbury** [comment]
It doesn't seem to do so. Simulations give different results with the same seed, but they're still deterministic. Had to tweak a few files to replace xrange with range and also modify the swig bindings. 

However, I've ended up going back to 2.7 due to slower performance.

In terms of the regex, it should just be more general and haven't seen it break. I've also used it with things like 3.6-dev and pyenv installed versions of python.

**Comment by cire831** [comment]
okay.  I'm okay with going ahead with this.   However....

I'm not okay with accepting any version of python which I beleive the patch will do.

I'd suggest you change it to recognize any version of 2.7 (one or two digits) and any version of 3

sound reasonable?

**Comment by MBradbury** [comment]
Sorry for the long gap, this got lost.

I've pushed a fix so that only Python 2 or Python 3 is matched.

**Comment by cire831** [comment]
no worries

thanks for making the effort

**Pull request merged**
